collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8100358
  brandStrength: 0.9229391
  lightness: 0.6487455
  brandColors:
    - '#191919'
    - '#2CF800'
    - '#3894BB'
    - '#FF7900'
    - '#9E571D'
  rhythmicContrast: 0.5555556
typography_spectrum: 0.4444444
layout_spectrum: 0.5017921
name: Wow
